openapi: 3.0.1
info:
  title: Registration 5G Meta API
  description: "APIs exposed to the registration module, in order to register a dataflow\
    \ before publishing it."
  version: 1.0.0
servers:
- url: /
tags:
- name: Registration API
paths:
  /dataflows:
    post:
      tags:
      - Registration API
      summary: Register a Dataflow
      operationId: add_dataflow
      requestBody:
        description: Dataflow metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataFlow'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "405":
          description: Bad Request
          content: {}
      x-openapi-router-controller: swagger_server.controllers.registration_api_controller
  /dataflows/{dataflowid}:
    put:
      tags:
      - Registration API
      summary: Update a registered a Dataflow
      operationId: update_dataflow
      parameters:
      - name: dataflowid
        in: path
        description: Id of the dataflow
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Dataflow metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataFlow'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "404":
          description: Not Found
          content: {}
        "405":
          description: Bad Request
          content: {}
      x-openapi-router-controller: swagger_server.controllers.registration_api_controller
    delete:
      tags:
      - Registration API
      summary: Delete a registered a Dataflow
      operationId: delete_dataflow
      parameters:
      - name: dataflowid
        in: path
        description: Id of the dataflow
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "404":
          description: Not Found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.registration_api_controller
components:
  schemas:
    DataFlow:
      required:
      - dataInfo
      - dataSourceInfo
      - dataTypeInfo
      - licenseInfo
      type: object
      properties:
        dataTypeInfo:
          $ref: '#/components/schemas/DataTypeInfo'
        dataInfo:
          $ref: '#/components/schemas/DataInfo'
        licenseInfo:
          $ref: '#/components/schemas/LicenseInfo'
        dataSourceInfo:
          $ref: '#/components/schemas/DataSourceInfo'
    DataInfo:
      required:
      - dataflowDirection
      - dataSampleRate
      type: object
      properties:
        dataflowDirection:
          type: string
        dataFormat:
          type: string
        dataSampleRate:
          type: number
        extraAttributes:
          type: string
          nullable: true
    LicenseInfo:
      required:
      - licenseGeolimit
      - licenseType
      type: object
      properties:
        licenseType:
          type: string
        licenseGeolimit:
          type: string
          enum: [local, edge, country, europe, world]
    SourceLocationInfo:
      required:
      - locationQuadkey
      type: object
      properties:
        locationCountry:
          type: string
          minLength: 3
          maxLength: 3
        locationLatitude:
          type: number
          minimum: -90
          maximum: 90
        locationLongitude:
          type: number
          minimum: -180
          maximum: 180
        locationQuadkey:
          type: string
          minLength: 18
          maxLength: 22
    DataSourceInfo:
      required:
      - sourceId
      - sourceLocationInfo
      - sourceType
      type: object
      properties:
        sourceId:
          type: integer
        sourceType:
          type: string
          default: vehicle
        sourceTimezone:
          type: integer
          minimum: -12
          maximum: 12
          nullable: true
        timeStratumLevel:
          type: integer
          minimum: 1
          maximum: 15
          nullable: true
        sourceLocationInfo:
          $ref: '#/components/schemas/SourceLocationInfo'
    DataTypeInfo:
      required:
      - dataSubType
      - dataType
      type: object
      properties:
        dataType:
          type: string
        dataSubType:
          type: string

