name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd src && docker build . --tag registrationapi:stable
      
    - name: Install python requirements
      run: pip3 install sqlalchemy==1.4.36 pymysql==1.0.2
      
    - name: Launch test
      run: cd tests && docker-compose up -d && sleep 20 && python3 sender/sender.py
      
  deploy:

    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd src && docker build . --tag 5gmeta/registration-api:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image
      run: docker push 5gmeta/registration-api:latest
      
      
